import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/** Seconds -> "MM:SS" (or "H:MM:SS"past an hour). Matches the transcript's
 *  evidence timestamps so a chip and a turn read the same way. */
export function formatSeconds(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return "00:00";
  const s = Math.floor(seconds % 60);
  const m = Math.floor((seconds / 60) % 60);
  const h = Math.floor(seconds / 3600);
  const mm = String(m).padStart(2, "0");
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}

/** "HH:MM:SS" or "MM:SS"-> seconds, for seeking from an evidence chip. */
export function parseTimestamp(timestamp: string): number {
  const parts = timestamp.split(":").map(Number);
  if (parts.some((n) => !Number.isFinite(n))) return 0;
  return parts.reduce((acc, part) => acc * 60 + part, 0);
}

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
] as const;

/** "2 Jun 2020, 01:04" — always UTC, always the same string.
 *
 *  Deliberately NOT `toLocaleString()`. That formats in the *runtime's* locale
 *  and timezone, so the server (a UTC container) and the browser (IST, en-US)
 *  produced different text for the same instant — "2/6/2020, 6:34:32 am" vs
 *  "6/2/2020, 1:04:32 AM" — which React reports as a hydration mismatch and
 *  then re-renders the whole subtree to recover.
 *
 *  Rendering UTC explicitly also removes the day/month ambiguity: these are
 *  2020 call records, and "6/2/2020" meaning two different dates depending on
 *  who is looking is worse than a slightly less familiar format.
 */
/** `pay_bill` -> `Pay bill`.
 *
 *  Intent labels are generated by the model as snake_case identifiers, which is
 *  the right shape for a database key and the wrong shape for the headline a
 *  support manager reads eight times on one screen. The stored value is
 *  untouched — this is presentation only, so the API contract and any downstream
 *  grouping still see the identifier.
 */
export function humanLabel(label: string | null | undefined): string {
  if (!label) return "Not analysed";
  const words = label.trim().replace(/[_-]+/g, " ").replace(/\s+/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function formatDateTime(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mm = String(d.getUTCMinutes()).padStart(2, "0");
  return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}, ${hh}:${mm}`;
}

/** Date only — "2 Jun 2020". Same UTC-fixed reasoning as above. */
export function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}

/** The score at which a call is put in front of a manager.
 *
 *  Mirrors the `attention_score >= 30` filter in backend/app/api/overview.py.
 *  The two must agree: a call the dashboard counts as needing a manager cannot
 *  be painted as if it were fine. */
export const NEEDS_MANAGER = 30;

/** Shared colour ramp for the 0-100 needs-attention score.
 *
 *  Bands are set from what this corpus can actually produce, not from a tidy
 *  75/50/25. Escalation language never fires here (0 hits in 8,866 customer
 *  turns) and mood severity almost never clears its floor, so the reachable
 *  ceiling is roughly resolution 30 + mood shift 15 + repeat 10 + handle time 5.
 *  Against that, a 75 threshold is unreachable and everything renders green —
 *  which is how a call sitting at the TOP of "worst calls" came to wear a green
 *  badge while the KPI beside it called the same call one that needs a manager.
 *
 *  Below the threshold is ink, not green. Green in this UI means "citation
 *  verified"; a low attention score is the absence of flags, not a success, and
 *  one colour cannot carry both claims. */
export function attentionTone(score: number | null): string {
  if (score === null)
    return "border-[var(--hairline)] text-[var(--ink-3)]";
  if (score >= 50)
    return "border-[var(--critical)]/60 bg-[var(--critical)]/10 text-[var(--critical)]";
  if (score >= NEEDS_MANAGER)
    return "border-[var(--warning)]/60 bg-[var(--warning)]/10 text-[var(--warning)]";
  return "border-[var(--hairline)] text-[var(--ink-2)]";
}
